image: node:10-alpine

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm install
  - npm run build
  - mv public public_old 
  - mv dist public
  artifacts:
    paths:
    - public
  only:
  - master
