name: Run Project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the repository
        run: |
          git clone https://github.com/Phar187/cuidando-do-meu-bairro-gp6.git
          cd cuidando-do-meu-bairro-gp6/website-vuejs

      - name: Update system packages
        run: sudo apt update && sudo apt upgrade -y

      - name: Install Git
        run: sudo apt install git -y

      - name: Install Python 2.7
        run: sudo apt install python2.7 -y

      # Instalar NVM e Node.js versão 14 (para compatibilidade)
      - name: Install NVM
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
          echo "source ~/.nvm/nvm.sh" >> $GITHUB_ENV  # Adiciona o nvm ao ambiente do GitHub Actions

      - name: Load NVM and Install Node.js 14
        run: |
          source ~/.nvm/nvm.sh
          nvm install 14
          nvm use 14
          node -v
          npm -v

      - name: Install Project Dependencies
        run: |
          cd cuidando-do-meu-bairro-gp6/website-vuejs
          npm install
          npm install leaflet vue2-leaflet

      - name: Run Project
        run: |
          cd cuidando-do-meu-bairro-gp6/website-vuejs
          npm run serve
        if: always()
