name: Setup and Run Project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # Atualizar pacotes do sistema
      - name: Update system packages
        run: sudo apt update && sudo apt upgrade -y

      # Instalar Git
      - name: Install Git
        run: sudo apt install git -y

      # Clonar o repositório
      - name: Clone the repository
        run: |
          git clone https://gitlab.com/cuidandodomeubairro/website-vuejs.git
          cd website-vuejs

      # Instalar Python 2.7
      - name: Install Python 2.7
        run: sudo apt install python2.7 -y

      # Usar Node.js 14 diretamente (sem NVM)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Usa diretamente a versão 14 do Node.js

      # Instalar dependências do projeto
      - name: Install Project Dependencies
        run: |
          cd website-vuejs
          npm install
          npm install leaflet vue2-leaflet

      # Executar o projeto
      - name: Run Project
        run: |
          cd website-vuejs
          npm run serve
          sleep 10  # Aguarda alguns segundos para verificar se es está rodando mesmo
        if: always()

# Finalizar o workflow após iniciar o projeto
      - name: Stop Workflow
        run: echo "terminando workflow após rodar o projeto"
        if: always()
